! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

module flc_set
 use, intrinsic :: ISO_C_BINDING
 use flc
 use flc_string
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! class std::set< int >
 type, public :: SetInt
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: empty => swigf_SetInt_empty
  procedure :: size => swigf_SetInt_size
  procedure :: clear => swigf_SetInt_clear
  procedure :: erase => swigf_SetInt_erase
  procedure :: count => swigf_SetInt_count
  procedure :: insert => swigf_SetInt_insert
  procedure :: release => swigf_release_SetInt
  procedure, private :: swigf_SetInt_op_assign__
  generic :: assignment(=) => swigf_SetInt_op_assign__
 end type SetInt
 interface SetInt
  module procedure swigf_create_SetInt
 end interface
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 ! class std::set< std::string >
 type, public :: SetString
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: empty => swigf_SetString_empty
  procedure :: size => swigf_SetString_size
  procedure :: clear => swigf_SetString_clear
  procedure :: erase => swigf_SetString_erase
  procedure :: count => swigf_SetString_count
  procedure :: insert => swigf_SetString_insert
  procedure :: release => swigf_release_SetString
  procedure, private :: swigf_SetString_op_assign__
  generic :: assignment(=) => swigf_SetString_op_assign__
 end type SetString
 interface SetString
  module procedure swigf_create_SetString
 end interface

! WRAPPER DECLARATIONS
interface
function swigc_new_SetInt() &
bind(C, name="_wrap_new_SetInt") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_SetInt_empty(farg1) &
bind(C, name="_wrap_SetInt_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_SetInt_size(farg1) &
bind(C, name="_wrap_SetInt_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SetInt_clear(farg1) &
bind(C, name="_wrap_SetInt_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

function swigc_SetInt_erase(farg1, farg2) &
bind(C, name="_wrap_SetInt_erase") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_LONG) :: fresult
end function

function swigc_SetInt_count(farg1, farg2) &
bind(C, name="_wrap_SetInt_count") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_LONG) :: fresult
end function

subroutine swigc_SetInt_insert(farg1, farg2) &
bind(C, name="_wrap_SetInt_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

subroutine swigc_delete_SetInt(farg1) &
bind(C, name="_wrap_delete_SetInt")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SetInt_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SetInt_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_new_SetString() &
bind(C, name="_wrap_new_SetString") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_SetString_empty(farg1) &
bind(C, name="_wrap_SetString_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_SetString_size(farg1) &
bind(C, name="_wrap_SetString_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SetString_clear(farg1) &
bind(C, name="_wrap_SetString_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

function swigc_SetString_erase(farg1, farg2) &
bind(C, name="_wrap_SetString_erase") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_LONG) :: fresult
end function

function swigc_SetString_count(farg1, farg2) &
bind(C, name="_wrap_SetString_count") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_LONG) :: fresult
end function

subroutine swigc_SetString_insert(farg1, farg2) &
bind(C, name="_wrap_SetString_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_delete_SetString(farg1) &
bind(C, name="_wrap_delete_SetString")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SetString_op_assign__(farg1, farg2) &
bind(C, name="_wrap_SetString_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
function swigf_create_SetInt() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SetInt) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SetInt()
self%swigdata = fresult
end function


subroutine SWIGTM_fout_bool(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  integer(kind=C_INT), intent(IN) :: imout
  logical, intent(OUT) :: fout
  ! TODO: fout = (imout /= 0) ???
  if (imout /= 0) then
    fout = .true.
  else
    fout = .false.
  end if
end subroutine

function swigf_SetInt_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(SetInt), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SetInt_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_SetInt_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(SetInt), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SetInt_size(farg1)
swig_result = int(fresult)
end function

subroutine swigf_SetInt_clear(self)
use, intrinsic :: ISO_C_BINDING
class(SetInt), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_SetInt_clear(farg1)
end subroutine

subroutine swigf_SetInt_erase(self, x, swig_result)
use, intrinsic :: ISO_C_BINDING
class(SetInt), intent(in) :: self
integer(C_INT), intent(in) :: x
integer, intent(out), optional :: swig_result
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = x
fresult = swigc_SetInt_erase(farg1, farg2)
if (present(swig_result)) then
swig_result = int(fresult)
endif

end subroutine

function swigf_SetInt_count(self, x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(SetInt), intent(in) :: self
integer(C_INT), intent(in) :: x
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = x
fresult = swigc_SetInt_count(farg1, farg2)
swig_result = int(fresult)
end function

subroutine swigf_SetInt_insert(self, x)
use, intrinsic :: ISO_C_BINDING
class(SetInt), intent(in) :: self
integer(C_INT), intent(in) :: x
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = x
call swigc_SetInt_insert(farg1, farg2)
end subroutine

subroutine swigf_release_SetInt(self)
use, intrinsic :: ISO_C_BINDING
class(SetInt), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SetInt(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SetInt_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SetInt), intent(inout) :: self
type(SetInt), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SetInt_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_create_SetString() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SetString) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SetString()
self%swigdata = fresult
end function

function swigf_SetString_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(SetString), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SetString_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_SetString_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(SetString), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SetString_size(farg1)
swig_result = int(fresult)
end function

subroutine swigf_SetString_clear(self)
use, intrinsic :: ISO_C_BINDING
class(SetString), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_SetString_clear(farg1)
end subroutine


subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(kind=C_CHAR, len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = finp(i:i)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

subroutine swigf_SetString_erase(self, x, swig_result)
use, intrinsic :: ISO_C_BINDING
class(SetString), intent(in) :: self
character(kind=C_CHAR, len=*), target :: x
integer, intent(out), optional :: swig_result
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_SetString_erase(farg1, farg2)
if (present(swig_result)) then
swig_result = int(fresult)
endif

end subroutine

function swigf_SetString_count(self, x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(SetString), intent(in) :: self
character(kind=C_CHAR, len=*), target :: x
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_SetString_count(farg1, farg2)
swig_result = int(fresult)
end function

subroutine swigf_SetString_insert(self, x)
use, intrinsic :: ISO_C_BINDING
class(SetString), intent(in) :: self
character(kind=C_CHAR, len=*), target :: x
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
call swigc_SetString_insert(farg1, farg2)
end subroutine

subroutine swigf_release_SetString(self)
use, intrinsic :: ISO_C_BINDING
class(SetString), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SetString(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SetString_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SetString), intent(inout) :: self
type(SetString), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SetString_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine


end module
