! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

module flc_vector
 use, intrinsic :: ISO_C_BINDING
 use flc
 use flc_string
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 ! class std::vector< int32_t >
 type, public :: VectorInt4
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: size => swigf_VectorInt4_size
  procedure :: capacity => swigf_VectorInt4_capacity
  procedure :: empty => swigf_VectorInt4_empty
  procedure :: front => swigf_VectorInt4_front
  procedure :: back => swigf_VectorInt4_back
  procedure :: reserve => swigf_VectorInt4_reserve
  procedure, private :: swigf_VectorInt4_resize__SWIG_0
  procedure, private :: swigf_VectorInt4_resize__SWIG_1
  procedure :: push_back => swigf_VectorInt4_push_back
  procedure :: pop_back => swigf_VectorInt4_pop_back
  procedure :: clear => swigf_VectorInt4_clear
  procedure :: set => swigf_VectorInt4_set
  procedure :: get => swigf_VectorInt4_get
  procedure :: insert => swigf_VectorInt4_insert
  procedure, private :: swigf_VectorInt4_erase__SWIG_0
  procedure, private :: swigf_VectorInt4_erase__SWIG_1
  procedure :: front_ref => swigf_VectorInt4_front_ref
  procedure :: back_ref => swigf_VectorInt4_back_ref
  procedure :: get_ref => swigf_VectorInt4_get_ref
  procedure :: assign => swigf_VectorInt4_assign
  procedure :: view => swigf_VectorInt4_view
  procedure :: release => swigf_release_VectorInt4
  procedure, private :: swigf_VectorInt4_op_assign__
  generic :: assignment(=) => swigf_VectorInt4_op_assign__
  generic :: resize => swigf_VectorInt4_resize__SWIG_0, swigf_VectorInt4_resize__SWIG_1
  generic :: erase => swigf_VectorInt4_erase__SWIG_0, swigf_VectorInt4_erase__SWIG_1
 end type VectorInt4
 interface VectorInt4
  module procedure swigf_new_VectorInt4__SWIG_0
  module procedure swigf_new_VectorInt4__SWIG_1
  module procedure swigf_new_VectorInt4__SWIG_2
  module procedure swigf_new_VectorInt4__SWIG_3
  module procedure swigf_new_VectorInt4__SWIG_4
 end interface
 ! class std::vector< int64_t >
 type, public :: VectorInt8
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: size => swigf_VectorInt8_size
  procedure :: capacity => swigf_VectorInt8_capacity
  procedure :: empty => swigf_VectorInt8_empty
  procedure :: front => swigf_VectorInt8_front
  procedure :: back => swigf_VectorInt8_back
  procedure :: reserve => swigf_VectorInt8_reserve
  procedure, private :: swigf_VectorInt8_resize__SWIG_0
  procedure, private :: swigf_VectorInt8_resize__SWIG_1
  procedure :: push_back => swigf_VectorInt8_push_back
  procedure :: pop_back => swigf_VectorInt8_pop_back
  procedure :: clear => swigf_VectorInt8_clear
  procedure :: set => swigf_VectorInt8_set
  procedure :: get => swigf_VectorInt8_get
  procedure :: insert => swigf_VectorInt8_insert
  procedure, private :: swigf_VectorInt8_erase__SWIG_0
  procedure, private :: swigf_VectorInt8_erase__SWIG_1
  procedure :: front_ref => swigf_VectorInt8_front_ref
  procedure :: back_ref => swigf_VectorInt8_back_ref
  procedure :: get_ref => swigf_VectorInt8_get_ref
  procedure :: assign => swigf_VectorInt8_assign
  procedure :: view => swigf_VectorInt8_view
  procedure :: release => swigf_release_VectorInt8
  procedure, private :: swigf_VectorInt8_op_assign__
  generic :: assignment(=) => swigf_VectorInt8_op_assign__
  generic :: resize => swigf_VectorInt8_resize__SWIG_0, swigf_VectorInt8_resize__SWIG_1
  generic :: erase => swigf_VectorInt8_erase__SWIG_0, swigf_VectorInt8_erase__SWIG_1
 end type VectorInt8
 interface VectorInt8
  module procedure swigf_new_VectorInt8__SWIG_0
  module procedure swigf_new_VectorInt8__SWIG_1
  module procedure swigf_new_VectorInt8__SWIG_2
  module procedure swigf_new_VectorInt8__SWIG_3
  module procedure swigf_new_VectorInt8__SWIG_4
 end interface
 ! class std::vector< double >
 type, public :: VectorReal8
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: size => swigf_VectorReal8_size
  procedure :: capacity => swigf_VectorReal8_capacity
  procedure :: empty => swigf_VectorReal8_empty
  procedure :: front => swigf_VectorReal8_front
  procedure :: back => swigf_VectorReal8_back
  procedure :: reserve => swigf_VectorReal8_reserve
  procedure, private :: swigf_VectorReal8_resize__SWIG_0
  procedure, private :: swigf_VectorReal8_resize__SWIG_1
  procedure :: push_back => swigf_VectorReal8_push_back
  procedure :: pop_back => swigf_VectorReal8_pop_back
  procedure :: clear => swigf_VectorReal8_clear
  procedure :: set => swigf_VectorReal8_set
  procedure :: get => swigf_VectorReal8_get
  procedure :: insert => swigf_VectorReal8_insert
  procedure, private :: swigf_VectorReal8_erase__SWIG_0
  procedure, private :: swigf_VectorReal8_erase__SWIG_1
  procedure :: front_ref => swigf_VectorReal8_front_ref
  procedure :: back_ref => swigf_VectorReal8_back_ref
  procedure :: get_ref => swigf_VectorReal8_get_ref
  procedure :: assign => swigf_VectorReal8_assign
  procedure :: view => swigf_VectorReal8_view
  procedure :: release => swigf_release_VectorReal8
  procedure, private :: swigf_VectorReal8_op_assign__
  generic :: assignment(=) => swigf_VectorReal8_op_assign__
  generic :: resize => swigf_VectorReal8_resize__SWIG_0, swigf_VectorReal8_resize__SWIG_1
  generic :: erase => swigf_VectorReal8_erase__SWIG_0, swigf_VectorReal8_erase__SWIG_1
 end type VectorReal8
 interface VectorReal8
  module procedure swigf_new_VectorReal8__SWIG_0
  module procedure swigf_new_VectorReal8__SWIG_1
  module procedure swigf_new_VectorReal8__SWIG_2
  module procedure swigf_new_VectorReal8__SWIG_3
  module procedure swigf_new_VectorReal8__SWIG_4
 end interface
 ! class std::vector< std::string >
 type, public :: VectorString
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: size => swigf_VectorString_size
  procedure :: capacity => swigf_VectorString_capacity
  procedure :: empty => swigf_VectorString_empty
  procedure :: front => swigf_VectorString_front
  procedure :: back => swigf_VectorString_back
  procedure :: reserve => swigf_VectorString_reserve
  procedure, private :: swigf_VectorString_resize__SWIG_0
  procedure, private :: swigf_VectorString_resize__SWIG_1
  procedure :: push_back => swigf_VectorString_push_back
  procedure :: pop_back => swigf_VectorString_pop_back
  procedure :: clear => swigf_VectorString_clear
  procedure :: set => swigf_VectorString_set
  procedure :: get => swigf_VectorString_get
  procedure :: insert => swigf_VectorString_insert
  procedure, private :: swigf_VectorString_erase__SWIG_0
  procedure, private :: swigf_VectorString_erase__SWIG_1
  procedure :: front_ref => swigf_VectorString_front_ref
  procedure :: back_ref => swigf_VectorString_back_ref
  procedure :: get_ref => swigf_VectorString_get_ref
  procedure :: set_ref => swigf_VectorString_set_ref
  procedure :: release => swigf_release_VectorString
  procedure, private :: swigf_VectorString_op_assign__
  generic :: assignment(=) => swigf_VectorString_op_assign__
  generic :: resize => swigf_VectorString_resize__SWIG_0, swigf_VectorString_resize__SWIG_1
  generic :: erase => swigf_VectorString_erase__SWIG_0, swigf_VectorString_erase__SWIG_1
 end type VectorString
 interface VectorString
  module procedure swigf_new_VectorString__SWIG_0
  module procedure swigf_new_VectorString__SWIG_1
  module procedure swigf_new_VectorString__SWIG_2
  module procedure swigf_new_VectorString__SWIG_3
 end interface

! WRAPPER DECLARATIONS
interface
function swigc_new_VectorInt4__SWIG_0() &
bind(C, name="_wrap_new_VectorInt4__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorInt4__SWIG_1(farg1) &
bind(C, name="_wrap_new_VectorInt4__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorInt4__SWIG_2(farg1) &
bind(C, name="_wrap_new_VectorInt4__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorInt4__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_new_VectorInt4__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
integer(C_INT32_T), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_VectorInt4_size(farg1) &
bind(C, name="_wrap_VectorInt4_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorInt4_capacity(farg1) &
bind(C, name="_wrap_VectorInt4_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorInt4_empty(farg1) &
bind(C, name="_wrap_VectorInt4_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_VectorInt4_front(farg1) &
bind(C, name="_wrap_VectorInt4_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T) :: fresult
end function

function swigc_VectorInt4_back(farg1) &
bind(C, name="_wrap_VectorInt4_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T) :: fresult
end function

subroutine swigc_VectorInt4_reserve(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_reserve")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt4_resize__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt4_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt4_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT32_T), intent(in) :: farg3
end subroutine

subroutine swigc_VectorInt4_push_back(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_push_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt4_pop_back(farg1) &
bind(C, name="_wrap_VectorInt4_pop_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorInt4_clear(farg1) &
bind(C, name="_wrap_VectorInt4_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorInt4_set(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt4_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT32_T), intent(in) :: farg3
end subroutine

function swigc_VectorInt4_get(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT32_T) :: fresult
end function

subroutine swigc_VectorInt4_insert(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt4_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT32_T), intent(in) :: farg3
end subroutine

subroutine swigc_VectorInt4_erase__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_erase__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt4_erase__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt4_erase__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG), intent(in) :: farg3
end subroutine

function swigc_VectorInt4_front_ref(farg1) &
bind(C, name="_wrap_VectorInt4_front_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_VectorInt4_back_ref(farg1) &
bind(C, name="_wrap_VectorInt4_back_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_VectorInt4_get_ref(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_get_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_new_VectorInt4__SWIG_4(farg1) &
bind(C, name="_wrap_new_VectorInt4__SWIG_4") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_VectorInt4_assign(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_assign")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

function swigc_VectorInt4_view(farg1) &
bind(C, name="_wrap_VectorInt4_view") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_delete_VectorInt4(farg1) &
bind(C, name="_wrap_delete_VectorInt4")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_VectorInt4_op_assign__(farg1, farg2) &
bind(C, name="_wrap_VectorInt4_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_new_VectorInt8__SWIG_0() &
bind(C, name="_wrap_new_VectorInt8__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorInt8__SWIG_1(farg1) &
bind(C, name="_wrap_new_VectorInt8__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorInt8__SWIG_2(farg1) &
bind(C, name="_wrap_new_VectorInt8__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorInt8__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_new_VectorInt8__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_VectorInt8_size(farg1) &
bind(C, name="_wrap_VectorInt8_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorInt8_capacity(farg1) &
bind(C, name="_wrap_VectorInt8_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorInt8_empty(farg1) &
bind(C, name="_wrap_VectorInt8_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_VectorInt8_front(farg1) &
bind(C, name="_wrap_VectorInt8_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_VectorInt8_back(farg1) &
bind(C, name="_wrap_VectorInt8_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT64_T) :: fresult
end function

subroutine swigc_VectorInt8_reserve(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_reserve")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt8_resize__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt8_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt8_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
end subroutine

subroutine swigc_VectorInt8_push_back(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_push_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT64_T), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt8_pop_back(farg1) &
bind(C, name="_wrap_VectorInt8_pop_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorInt8_clear(farg1) &
bind(C, name="_wrap_VectorInt8_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorInt8_set(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt8_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
end subroutine

function swigc_VectorInt8_get(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT64_T) :: fresult
end function

subroutine swigc_VectorInt8_insert(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt8_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
end subroutine

subroutine swigc_VectorInt8_erase__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_erase__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt8_erase__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorInt8_erase__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG), intent(in) :: farg3
end subroutine

function swigc_VectorInt8_front_ref(farg1) &
bind(C, name="_wrap_VectorInt8_front_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_VectorInt8_back_ref(farg1) &
bind(C, name="_wrap_VectorInt8_back_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_VectorInt8_get_ref(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_get_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_new_VectorInt8__SWIG_4(farg1) &
bind(C, name="_wrap_new_VectorInt8__SWIG_4") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_VectorInt8_assign(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_assign")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

function swigc_VectorInt8_view(farg1) &
bind(C, name="_wrap_VectorInt8_view") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_delete_VectorInt8(farg1) &
bind(C, name="_wrap_delete_VectorInt8")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_VectorInt8_op_assign__(farg1, farg2) &
bind(C, name="_wrap_VectorInt8_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_new_VectorReal8__SWIG_0() &
bind(C, name="_wrap_new_VectorReal8__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorReal8__SWIG_1(farg1) &
bind(C, name="_wrap_new_VectorReal8__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorReal8__SWIG_2(farg1) &
bind(C, name="_wrap_new_VectorReal8__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorReal8__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_new_VectorReal8__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_VectorReal8_size(farg1) &
bind(C, name="_wrap_VectorReal8_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorReal8_capacity(farg1) &
bind(C, name="_wrap_VectorReal8_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorReal8_empty(farg1) &
bind(C, name="_wrap_VectorReal8_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_VectorReal8_front(farg1) &
bind(C, name="_wrap_VectorReal8_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

function swigc_VectorReal8_back(farg1) &
bind(C, name="_wrap_VectorReal8_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_VectorReal8_reserve(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_reserve")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorReal8_resize__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorReal8_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorReal8_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

subroutine swigc_VectorReal8_push_back(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_push_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

subroutine swigc_VectorReal8_pop_back(farg1) &
bind(C, name="_wrap_VectorReal8_pop_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorReal8_clear(farg1) &
bind(C, name="_wrap_VectorReal8_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorReal8_set(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorReal8_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

function swigc_VectorReal8_get(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE) :: fresult
end function

subroutine swigc_VectorReal8_insert(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorReal8_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

subroutine swigc_VectorReal8_erase__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_erase__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorReal8_erase__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorReal8_erase__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG), intent(in) :: farg3
end subroutine

function swigc_VectorReal8_front_ref(farg1) &
bind(C, name="_wrap_VectorReal8_front_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_VectorReal8_back_ref(farg1) &
bind(C, name="_wrap_VectorReal8_back_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_VectorReal8_get_ref(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_get_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_new_VectorReal8__SWIG_4(farg1) &
bind(C, name="_wrap_new_VectorReal8__SWIG_4") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_VectorReal8_assign(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_assign")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

function swigc_VectorReal8_view(farg1) &
bind(C, name="_wrap_VectorReal8_view") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_delete_VectorReal8(farg1) &
bind(C, name="_wrap_delete_VectorReal8")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_VectorReal8_op_assign__(farg1, farg2) &
bind(C, name="_wrap_VectorReal8_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_new_VectorString__SWIG_0() &
bind(C, name="_wrap_new_VectorString__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorString__SWIG_1(farg1) &
bind(C, name="_wrap_new_VectorString__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorString__SWIG_2(farg1) &
bind(C, name="_wrap_new_VectorString__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_LONG), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_VectorString__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_new_VectorString__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
integer(C_LONG), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_VectorString_size(farg1) &
bind(C, name="_wrap_VectorString_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorString_capacity(farg1) &
bind(C, name="_wrap_VectorString_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorString_empty(farg1) &
bind(C, name="_wrap_VectorString_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_VectorString_front(farg1) &
bind(C, name="_wrap_VectorString_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function

function swigc_VectorString_back(farg1) &
bind(C, name="_wrap_VectorString_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_VectorString_reserve(farg1, farg2) &
bind(C, name="_wrap_VectorString_reserve")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorString_resize__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorString_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorString_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorString_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_VectorString_push_back(farg1, farg2) &
bind(C, name="_wrap_VectorString_push_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_VectorString_pop_back(farg1) &
bind(C, name="_wrap_VectorString_pop_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorString_clear(farg1) &
bind(C, name="_wrap_VectorString_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_VectorString_set(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorString_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

function swigc_VectorString_get(farg1, farg2) &
bind(C, name="_wrap_VectorString_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_VectorString_insert(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorString_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_VectorString_erase__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_VectorString_erase__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorString_erase__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorString_erase__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG), intent(in) :: farg3
end subroutine

function swigc_VectorString_front_ref(farg1) &
bind(C, name="_wrap_VectorString_front_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_VectorString_back_ref(farg1) &
bind(C, name="_wrap_VectorString_back_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_VectorString_get_ref(farg1, farg2) &
bind(C, name="_wrap_VectorString_get_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_VectorString_set_ref(farg1, farg2, farg3) &
bind(C, name="_wrap_VectorString_set_ref")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

subroutine swigc_delete_VectorString(farg1) &
bind(C, name="_wrap_delete_VectorString")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_VectorString_op_assign__(farg1, farg2) &
bind(C, name="_wrap_VectorString_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
function swigf_new_VectorInt4__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt4) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_VectorInt4__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_VectorInt4__SWIG_1(other) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt4) :: self
class(VectorInt4), intent(in) :: other
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = other%swigdata
fresult = swigc_new_VectorInt4__SWIG_1(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorInt4__SWIG_2(count) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt4) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 

farg1 = int(count, C_INT)
fresult = swigc_new_VectorInt4__SWIG_2(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorInt4__SWIG_3(count, v) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt4) :: self
integer, intent(in) :: count
integer(C_INT32_T), intent(in) :: v
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 
integer(C_INT32_T) :: farg2 

farg1 = int(count, C_INT)
farg2 = v
fresult = swigc_new_VectorInt4__SWIG_3(farg1, farg2)
self%swigdata = fresult
end function

function swigf_VectorInt4_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorInt4), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_size(farg1)
swig_result = int(fresult)
end function

function swigf_VectorInt4_capacity(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorInt4), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_capacity(farg1)
swig_result = int(fresult)
end function


subroutine SWIGTM_fout_bool(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  integer(kind=C_INT), intent(IN) :: imout
  logical, intent(OUT) :: fout
  ! TODO: fout = (imout /= 0) ???
  if (imout /= 0) then
    fout = .true.
  else
    fout = .false.
  end if
end subroutine

function swigf_VectorInt4_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(VectorInt4), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_VectorInt4_front(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T) :: swig_result
class(VectorInt4), intent(in) :: self
integer(C_INT32_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_front(farg1)
swig_result = fresult
end function

function swigf_VectorInt4_back(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T) :: swig_result
class(VectorInt4), intent(in) :: self
integer(C_INT32_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_back(farg1)
swig_result = fresult
end function

subroutine swigf_VectorInt4_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorInt4_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorInt4_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorInt4_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorInt4_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: count
integer(C_INT32_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT32_T) :: farg3 

farg1 = self%swigdata
farg2 = int(count, C_INT)
farg3 = v
call swigc_VectorInt4_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorInt4_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer(C_INT32_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_INT32_T) :: farg2 

farg1 = self%swigdata
farg2 = v
call swigc_VectorInt4_push_back(farg1, farg2)
end subroutine

subroutine swigf_VectorInt4_pop_back(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorInt4_pop_back(farg1)
end subroutine

subroutine swigf_VectorInt4_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorInt4_clear(farg1)
end subroutine

subroutine swigf_VectorInt4_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: index
integer(C_INT32_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT32_T) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v
call swigc_VectorInt4_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorInt4_get(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T) :: swig_result
class(VectorInt4), intent(in) :: self
integer, intent(in) :: index
integer(C_INT32_T) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorInt4_get(farg1, farg2)
swig_result = fresult
end function

subroutine swigf_VectorInt4_insert(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: index
integer(C_INT32_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT32_T) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v
call swigc_VectorInt4_insert(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorInt4_erase__SWIG_0(self, index)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call swigc_VectorInt4_erase__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorInt4_erase__SWIG_1(self, start_index, stop_index)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer, intent(in) :: start_index
integer, intent(in) :: stop_index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_LONG) :: farg3 

farg1 = self%swigdata
farg2 = int(start_index, C_INT)
farg3 = int(stop_index, C_INT)
call swigc_VectorInt4_erase__SWIG_1(farg1, farg2, farg3)
end subroutine

function swigf_VectorInt4_front_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), pointer :: swig_result
class(VectorInt4), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_front_ref(farg1)
call c_f_pointer(fresult, swig_result)
end function

function swigf_VectorInt4_back_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), pointer :: swig_result
class(VectorInt4), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_back_ref(farg1)
call c_f_pointer(fresult, swig_result)
end function

function swigf_VectorInt4_get_ref(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), pointer :: swig_result
class(VectorInt4), intent(in) :: self
integer, intent(in) :: index
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorInt4_get_ref(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

subroutine SWIGTM_fin_int32_t_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  integer(C_INT32_T), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  integer(C_INT32_T), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
function swigf_new_VectorInt4__SWIG_4(data) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt4) :: self
integer(C_INT32_T), dimension(:), intent(in), target :: data
type(SwigClassWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
fresult = swigc_new_VectorInt4__SWIG_4(farg1)
self%swigdata = fresult
end function

subroutine swigf_VectorInt4_assign(self, data)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(in) :: self
integer(C_INT32_T), dimension(:), intent(in), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_int32_t_Sb__SB_(data, farg2)
call swigc_VectorInt4_assign(farg1, farg2)
end subroutine

subroutine SWIGTM_fout_int32_t_Sb__SB_(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(in) :: imout
  integer(C_INT32_T), dimension(:), pointer, intent(out) :: fout

  if (imout%size > 0) then
    call c_f_pointer(imout%data, fout, [imout%size])
  else
    fout => NULL()
  endif
end subroutine
function swigf_VectorInt4_view(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), pointer :: swig_result
class(VectorInt4), intent(in) :: self
type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt4_view(farg1)
call SWIGTM_fout_int32_t_Sb__SB_(fresult, swig_result)
end function

subroutine swigf_release_VectorInt4(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_VectorInt4(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_VectorInt4_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(VectorInt4), intent(inout) :: self
type(VectorInt4), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_VectorInt4_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_new_VectorInt8__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt8) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_VectorInt8__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_VectorInt8__SWIG_1(other) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt8) :: self
class(VectorInt8), intent(in) :: other
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = other%swigdata
fresult = swigc_new_VectorInt8__SWIG_1(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorInt8__SWIG_2(count) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt8) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 

farg1 = int(count, C_INT)
fresult = swigc_new_VectorInt8__SWIG_2(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorInt8__SWIG_3(count, v) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt8) :: self
integer, intent(in) :: count
integer(C_INT64_T), intent(in) :: v
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = int(count, C_INT)
farg2 = v
fresult = swigc_new_VectorInt8__SWIG_3(farg1, farg2)
self%swigdata = fresult
end function

function swigf_VectorInt8_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorInt8), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_size(farg1)
swig_result = int(fresult)
end function

function swigf_VectorInt8_capacity(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorInt8), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_capacity(farg1)
swig_result = int(fresult)
end function

function swigf_VectorInt8_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(VectorInt8), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_VectorInt8_front(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(VectorInt8), intent(in) :: self
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_front(farg1)
swig_result = fresult
end function

function swigf_VectorInt8_back(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(VectorInt8), intent(in) :: self
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_back(farg1)
swig_result = fresult
end function

subroutine swigf_VectorInt8_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorInt8_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorInt8_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorInt8_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorInt8_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: count
integer(C_INT64_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT64_T) :: farg3 

farg1 = self%swigdata
farg2 = int(count, C_INT)
farg3 = v
call swigc_VectorInt8_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorInt8_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer(C_INT64_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = self%swigdata
farg2 = v
call swigc_VectorInt8_push_back(farg1, farg2)
end subroutine

subroutine swigf_VectorInt8_pop_back(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorInt8_pop_back(farg1)
end subroutine

subroutine swigf_VectorInt8_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorInt8_clear(farg1)
end subroutine

subroutine swigf_VectorInt8_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: index
integer(C_INT64_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT64_T) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v
call swigc_VectorInt8_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorInt8_get(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(VectorInt8), intent(in) :: self
integer, intent(in) :: index
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorInt8_get(farg1, farg2)
swig_result = fresult
end function

subroutine swigf_VectorInt8_insert(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: index
integer(C_INT64_T), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT64_T) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v
call swigc_VectorInt8_insert(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorInt8_erase__SWIG_0(self, index)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call swigc_VectorInt8_erase__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorInt8_erase__SWIG_1(self, start_index, stop_index)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer, intent(in) :: start_index
integer, intent(in) :: stop_index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_LONG) :: farg3 

farg1 = self%swigdata
farg2 = int(start_index, C_INT)
farg3 = int(stop_index, C_INT)
call swigc_VectorInt8_erase__SWIG_1(farg1, farg2, farg3)
end subroutine

function swigf_VectorInt8_front_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), pointer :: swig_result
class(VectorInt8), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_front_ref(farg1)
call c_f_pointer(fresult, swig_result)
end function

function swigf_VectorInt8_back_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), pointer :: swig_result
class(VectorInt8), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_back_ref(farg1)
call c_f_pointer(fresult, swig_result)
end function

function swigf_VectorInt8_get_ref(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), pointer :: swig_result
class(VectorInt8), intent(in) :: self
integer, intent(in) :: index
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorInt8_get_ref(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

subroutine SWIGTM_fin_int64_t_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  integer(C_INT64_T), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  integer(C_INT64_T), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
function swigf_new_VectorInt8__SWIG_4(data) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorInt8) :: self
integer(C_INT64_T), dimension(:), intent(in), target :: data
type(SwigClassWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
fresult = swigc_new_VectorInt8__SWIG_4(farg1)
self%swigdata = fresult
end function

subroutine swigf_VectorInt8_assign(self, data)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(in) :: self
integer(C_INT64_T), dimension(:), intent(in), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_int64_t_Sb__SB_(data, farg2)
call swigc_VectorInt8_assign(farg1, farg2)
end subroutine

subroutine SWIGTM_fout_int64_t_Sb__SB_(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(in) :: imout
  integer(C_INT64_T), dimension(:), pointer, intent(out) :: fout

  if (imout%size > 0) then
    call c_f_pointer(imout%data, fout, [imout%size])
  else
    fout => NULL()
  endif
end subroutine
function swigf_VectorInt8_view(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), pointer :: swig_result
class(VectorInt8), intent(in) :: self
type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorInt8_view(farg1)
call SWIGTM_fout_int64_t_Sb__SB_(fresult, swig_result)
end function

subroutine swigf_release_VectorInt8(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_VectorInt8(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_VectorInt8_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(VectorInt8), intent(inout) :: self
type(VectorInt8), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_VectorInt8_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_new_VectorReal8__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorReal8) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_VectorReal8__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_VectorReal8__SWIG_1(other) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorReal8) :: self
class(VectorReal8), intent(in) :: other
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = other%swigdata
fresult = swigc_new_VectorReal8__SWIG_1(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorReal8__SWIG_2(count) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorReal8) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 

farg1 = int(count, C_INT)
fresult = swigc_new_VectorReal8__SWIG_2(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorReal8__SWIG_3(count, v) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorReal8) :: self
integer, intent(in) :: count
real(C_DOUBLE), intent(in) :: v
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = int(count, C_INT)
farg2 = v
fresult = swigc_new_VectorReal8__SWIG_3(farg1, farg2)
self%swigdata = fresult
end function

function swigf_VectorReal8_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorReal8), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_size(farg1)
swig_result = int(fresult)
end function

function swigf_VectorReal8_capacity(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorReal8), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_capacity(farg1)
swig_result = int(fresult)
end function

function swigf_VectorReal8_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(VectorReal8), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_VectorReal8_front(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(VectorReal8), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_front(farg1)
swig_result = fresult
end function

function swigf_VectorReal8_back(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(VectorReal8), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_back(farg1)
swig_result = fresult
end function

subroutine swigf_VectorReal8_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorReal8_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorReal8_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorReal8_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorReal8_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: count
real(C_DOUBLE), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigdata
farg2 = int(count, C_INT)
farg3 = v
call swigc_VectorReal8_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorReal8_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
real(C_DOUBLE), intent(in) :: v
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = v
call swigc_VectorReal8_push_back(farg1, farg2)
end subroutine

subroutine swigf_VectorReal8_pop_back(self)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorReal8_pop_back(farg1)
end subroutine

subroutine swigf_VectorReal8_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorReal8_clear(farg1)
end subroutine

subroutine swigf_VectorReal8_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: index
real(C_DOUBLE), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v
call swigc_VectorReal8_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorReal8_get(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(VectorReal8), intent(in) :: self
integer, intent(in) :: index
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorReal8_get(farg1, farg2)
swig_result = fresult
end function

subroutine swigf_VectorReal8_insert(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: index
real(C_DOUBLE), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v
call swigc_VectorReal8_insert(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorReal8_erase__SWIG_0(self, index)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call swigc_VectorReal8_erase__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorReal8_erase__SWIG_1(self, start_index, stop_index)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
integer, intent(in) :: start_index
integer, intent(in) :: stop_index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_LONG) :: farg3 

farg1 = self%swigdata
farg2 = int(start_index, C_INT)
farg3 = int(stop_index, C_INT)
call swigc_VectorReal8_erase__SWIG_1(farg1, farg2, farg3)
end subroutine

function swigf_VectorReal8_front_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), pointer :: swig_result
class(VectorReal8), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_front_ref(farg1)
call c_f_pointer(fresult, swig_result)
end function

function swigf_VectorReal8_back_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), pointer :: swig_result
class(VectorReal8), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_back_ref(farg1)
call c_f_pointer(fresult, swig_result)
end function

function swigf_VectorReal8_get_ref(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), pointer :: swig_result
class(VectorReal8), intent(in) :: self
integer, intent(in) :: index
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorReal8_get_ref(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

subroutine SWIGTM_fin_double_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  real(C_DOUBLE), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  real(C_DOUBLE), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
function swigf_new_VectorReal8__SWIG_4(data) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorReal8) :: self
real(C_DOUBLE), dimension(:), intent(in), target :: data
type(SwigClassWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
fresult = swigc_new_VectorReal8__SWIG_4(farg1)
self%swigdata = fresult
end function

subroutine swigf_VectorReal8_assign(self, data)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(in) :: self
real(C_DOUBLE), dimension(:), intent(in), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_double_Sb__SB_(data, farg2)
call swigc_VectorReal8_assign(farg1, farg2)
end subroutine

subroutine SWIGTM_fout_double_Sb__SB_(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(in) :: imout
  real(C_DOUBLE), dimension(:), pointer, intent(out) :: fout

  if (imout%size > 0) then
    call c_f_pointer(imout%data, fout, [imout%size])
  else
    fout => NULL()
  endif
end subroutine
function swigf_VectorReal8_view(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
class(VectorReal8), intent(in) :: self
type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorReal8_view(farg1)
call SWIGTM_fout_double_Sb__SB_(fresult, swig_result)
end function

subroutine swigf_release_VectorReal8(self)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_VectorReal8(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_VectorReal8_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(VectorReal8), intent(inout) :: self
type(VectorReal8), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_VectorReal8_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_new_VectorString__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorString) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_VectorString__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_VectorString__SWIG_1(other) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorString) :: self
class(VectorString), intent(in) :: other
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = other%swigdata
fresult = swigc_new_VectorString__SWIG_1(farg1)
self%swigdata = fresult
end function

function swigf_new_VectorString__SWIG_2(count) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorString) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 

farg1 = int(count, C_INT)
fresult = swigc_new_VectorString__SWIG_2(farg1)
self%swigdata = fresult
end function


subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(kind=C_CHAR, len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = finp(i:i)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

function swigf_new_VectorString__SWIG_3(count, v) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(VectorString) :: self
integer, intent(in) :: count
character(kind=C_CHAR, len=*), target :: v
type(SwigClassWrapper) :: fresult 
integer(C_LONG) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = int(count, C_INT)
call SWIGTM_fin_char_Sm_(v, farg2, farg2_temp)
fresult = swigc_new_VectorString__SWIG_3(farg1, farg2)
self%swigdata = fresult
end function

function swigf_VectorString_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorString), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_size(farg1)
swig_result = int(fresult)
end function

function swigf_VectorString_capacity(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(VectorString), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_capacity(farg1)
swig_result = int(fresult)
end function

function swigf_VectorString_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(VectorString), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function


subroutine SWIGTM_fout_char_Sm_(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(in) :: imout
  character(kind=C_CHAR, len=:), allocatable, intent(out) :: fout
  character(kind=C_CHAR), dimension(:), pointer :: chars
  integer(kind=C_SIZE_T) :: i
  call c_f_pointer(imout%data, chars, [imout%size])
  allocate(character(kind=C_CHAR, len=imout%size) :: fout)
  do i=1, imout%size
    fout(i:i) = chars(i)
  end do
end subroutine

function swigf_VectorString_front(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
class(VectorString), intent(in) :: self
type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_front(farg1)
call SWIGTM_fout_char_Sm_(fresult, swig_result)
end function

function swigf_VectorString_back(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
class(VectorString), intent(in) :: self
type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_back(farg1)
call SWIGTM_fout_char_Sm_(fresult, swig_result)
end function

subroutine swigf_VectorString_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorString_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorString_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_VectorString_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorString_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: count
character(kind=C_CHAR, len=*), target :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
call swigc_VectorString_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorString_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
character(kind=C_CHAR, len=*), target :: v
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIGTM_fin_char_Sm_(v, farg2, farg2_temp)
call swigc_VectorString_push_back(farg1, farg2)
end subroutine

subroutine swigf_VectorString_pop_back(self)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorString_pop_back(farg1)
end subroutine

subroutine swigf_VectorString_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_VectorString_clear(farg1)
end subroutine

subroutine swigf_VectorString_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: index
character(kind=C_CHAR, len=*), target :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
call swigc_VectorString_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorString_get(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
class(VectorString), intent(in) :: self
integer, intent(in) :: index
type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorString_get(farg1, farg2)
call SWIGTM_fout_char_Sm_(fresult, swig_result)
end function

subroutine swigf_VectorString_insert(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: index
character(kind=C_CHAR, len=*), target :: v
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
call swigc_VectorString_insert(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorString_erase__SWIG_0(self, index)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call swigc_VectorString_erase__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorString_erase__SWIG_1(self, start_index, stop_index)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: start_index
integer, intent(in) :: stop_index
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
integer(C_LONG) :: farg3 

farg1 = self%swigdata
farg2 = int(start_index, C_INT)
farg3 = int(stop_index, C_INT)
call swigc_VectorString_erase__SWIG_1(farg1, farg2, farg3)
end subroutine

function swigf_VectorString_front_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(string) :: swig_result
class(VectorString), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_front_ref(farg1)
swig_result%swigdata = fresult
end function

function swigf_VectorString_back_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(string) :: swig_result
class(VectorString), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_VectorString_back_ref(farg1)
swig_result%swigdata = fresult
end function

function swigf_VectorString_get_ref(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(string) :: swig_result
class(VectorString), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_VectorString_get_ref(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine swigf_VectorString_set_ref(self, index, str)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(in) :: self
integer, intent(in) :: index
class(string), intent(in) :: str
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = str%swigdata
call swigc_VectorString_set_ref(farg1, farg2, farg3)
end subroutine

subroutine swigf_release_VectorString(self)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_VectorString(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_VectorString_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(VectorString), intent(inout) :: self
type(VectorString), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_VectorString_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine


end module
