! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

module flc_algorithm
 use, intrinsic :: ISO_C_BINDING
 use flc
 use flc_random
 implicit none
 private

 ! DECLARATION CONSTRUCTS
integer, parameter, public :: INDEX_INT = C_INT

 public :: flc_cmp_int4
 public :: flc_cmp_int8
 public :: flc_cmp_real8
 public :: flc_cmp_index
 public :: flc_cmp_ptr
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 interface binary_search
  module procedure swigf_binary_search__SWIG_1, swigf_binary_search__SWIG_2, swigf_binary_search__SWIG_3, &
    swigf_binary_search__SWIG_4, swigf_binary_search__SWIG_5, swigf_binary_search__SWIG_6, swigf_binary_search__SWIG_7
 end interface
 public :: binary_search
 interface minmax_element
  module procedure swigf_minmax_element__SWIG_1, swigf_minmax_element__SWIG_2, swigf_minmax_element__SWIG_3, &
    swigf_minmax_element__SWIG_4, swigf_minmax_element__SWIG_5, swigf_minmax_element__SWIG_6, swigf_minmax_element__SWIG_7
 end interface
 public :: minmax_element
 interface shuffle
  module procedure swigf_shuffle__SWIG_1, swigf_shuffle__SWIG_2, swigf_shuffle__SWIG_3, swigf_shuffle__SWIG_4
 end interface
 public :: shuffle
 interface includes
  module procedure swigf_includes__SWIG_1, swigf_includes__SWIG_2, swigf_includes__SWIG_3, swigf_includes__SWIG_4, &
    swigf_includes__SWIG_5, swigf_includes__SWIG_6, swigf_includes__SWIG_7
 end interface
 public :: includes
 interface is_sorted
  module procedure swigf_is_sorted__SWIG_1, swigf_is_sorted__SWIG_2, swigf_is_sorted__SWIG_3, swigf_is_sorted__SWIG_4, &
    swigf_is_sorted__SWIG_5, swigf_is_sorted__SWIG_6, swigf_is_sorted__SWIG_7
 end interface
 public :: is_sorted
 interface equal_range
  module procedure swigf_equal_range__SWIG_1, swigf_equal_range__SWIG_2, swigf_equal_range__SWIG_3, swigf_equal_range__SWIG_4, &
    swigf_equal_range__SWIG_5, swigf_equal_range__SWIG_6, swigf_equal_range__SWIG_7
 end interface
 public :: equal_range
 interface sort
  module procedure swigf_sort__SWIG_1, swigf_sort__SWIG_2, swigf_sort__SWIG_3, swigf_sort__SWIG_4, swigf_sort__SWIG_5, &
    swigf_sort__SWIG_6, swigf_sort__SWIG_7
 end interface
 public :: sort
 interface argsort
  module procedure swigf_argsort__SWIG_1, swigf_argsort__SWIG_2, swigf_argsort__SWIG_3, swigf_argsort__SWIG_4, &
    swigf_argsort__SWIG_5, swigf_argsort__SWIG_6, swigf_argsort__SWIG_7
 end interface
 public :: argsort

! FUNCTION POINTER DECLARATIONS
abstract interface
function flc_cmp_int4(left, right) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: left
integer(C_INT32_T), intent(in), value :: right
logical(C_BOOL) :: fresult
end function

function flc_cmp_int8(left, right) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), intent(in), value :: left
integer(C_INT64_T), intent(in), value :: right
logical(C_BOOL) :: fresult
end function

function flc_cmp_real8(left, right) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in), value :: left
real(C_DOUBLE), intent(in), value :: right
logical(C_BOOL) :: fresult
end function

function flc_cmp_index(left, right) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: left
integer(C_INT), intent(in), value :: right
logical(C_BOOL) :: fresult
end function

function flc_cmp_ptr(left, right) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in), value :: left
type(C_PTR), intent(in), value :: right
logical(C_BOOL) :: fresult
end function

end interface


! WRAPPER DECLARATIONS
interface
subroutine swigc_sort__SWIG_1(farg1) &
bind(C, name="_wrap_sort__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
end subroutine

subroutine swigc_sort__SWIG_2(farg1) &
bind(C, name="_wrap_sort__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
end subroutine

subroutine swigc_sort__SWIG_3(farg1) &
bind(C, name="_wrap_sort__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
end subroutine

subroutine swigc_sort__SWIG_4(farg1, farg3) &
bind(C, name="_wrap_sort__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
end subroutine

subroutine swigc_sort__SWIG_5(farg1, farg3) &
bind(C, name="_wrap_sort__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
end subroutine

subroutine swigc_sort__SWIG_6(farg1, farg3) &
bind(C, name="_wrap_sort__SWIG_6")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
end subroutine

subroutine swigc_sort__SWIG_7(farg1, farg3) &
bind(C, name="_wrap_sort__SWIG_7")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
end subroutine

function swigc_is_sorted__SWIG_1(farg1) &
bind(C, name="_wrap_is_sorted__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_is_sorted__SWIG_2(farg1) &
bind(C, name="_wrap_is_sorted__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_is_sorted__SWIG_3(farg1) &
bind(C, name="_wrap_is_sorted__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_is_sorted__SWIG_4(farg1, farg3) &
bind(C, name="_wrap_is_sorted__SWIG_4") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_is_sorted__SWIG_5(farg1, farg3) &
bind(C, name="_wrap_is_sorted__SWIG_5") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_is_sorted__SWIG_6(farg1, farg3) &
bind(C, name="_wrap_is_sorted__SWIG_6") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_is_sorted__SWIG_7(farg1, farg3) &
bind(C, name="_wrap_is_sorted__SWIG_7") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_FUNPTR), value :: farg3
integer(C_INT) :: fresult
end function

subroutine swigc_argsort__SWIG_1(farg1, farg3) &
bind(C, name="_wrap_argsort__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_argsort__SWIG_2(farg1, farg3) &
bind(C, name="_wrap_argsort__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_argsort__SWIG_3(farg1, farg3) &
bind(C, name="_wrap_argsort__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_argsort__SWIG_4(farg1, farg3, farg5) &
bind(C, name="_wrap_argsort__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
end subroutine

subroutine swigc_argsort__SWIG_5(farg1, farg3, farg5) &
bind(C, name="_wrap_argsort__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
end subroutine

subroutine swigc_argsort__SWIG_6(farg1, farg3, farg5) &
bind(C, name="_wrap_argsort__SWIG_6")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
end subroutine

subroutine swigc_argsort__SWIG_7(farg1, farg3, farg5) &
bind(C, name="_wrap_argsort__SWIG_7")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
end subroutine

function swigc_binary_search__SWIG_1(farg1, farg3) &
bind(C, name="_wrap_binary_search__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_binary_search__SWIG_2(farg1, farg3) &
bind(C, name="_wrap_binary_search__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT64_T), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_binary_search__SWIG_3(farg1, farg3) &
bind(C, name="_wrap_binary_search__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_binary_search__SWIG_4(farg1, farg3, farg4) &
bind(C, name="_wrap_binary_search__SWIG_4") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg3
type(C_FUNPTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_binary_search__SWIG_5(farg1, farg3, farg4) &
bind(C, name="_wrap_binary_search__SWIG_5") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT64_T), intent(in) :: farg3
type(C_FUNPTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_binary_search__SWIG_6(farg1, farg3, farg4) &
bind(C, name="_wrap_binary_search__SWIG_6") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg3
type(C_FUNPTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_binary_search__SWIG_7(farg1, farg3, farg4) &
bind(C, name="_wrap_binary_search__SWIG_7") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), intent(in) :: farg3
type(C_FUNPTR), value :: farg4
integer(C_INT) :: fresult
end function

subroutine swigc_equal_range__SWIG_1(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_equal_range__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
end subroutine

subroutine swigc_equal_range__SWIG_2(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_equal_range__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT64_T), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
end subroutine

subroutine swigc_equal_range__SWIG_3(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_equal_range__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
end subroutine

subroutine swigc_equal_range__SWIG_4(farg1, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_equal_range__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_FUNPTR), value :: farg6
end subroutine

subroutine swigc_equal_range__SWIG_5(farg1, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_equal_range__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT64_T), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_FUNPTR), value :: farg6
end subroutine

subroutine swigc_equal_range__SWIG_6(farg1, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_equal_range__SWIG_6")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_FUNPTR), value :: farg6
end subroutine

subroutine swigc_equal_range__SWIG_7(farg1, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_equal_range__SWIG_7")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_FUNPTR), value :: farg6
end subroutine

subroutine swigc_minmax_element__SWIG_1(farg1, farg3, farg4) &
bind(C, name="_wrap_minmax_element__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
end subroutine

subroutine swigc_minmax_element__SWIG_2(farg1, farg3, farg4) &
bind(C, name="_wrap_minmax_element__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
end subroutine

subroutine swigc_minmax_element__SWIG_3(farg1, farg3, farg4) &
bind(C, name="_wrap_minmax_element__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
end subroutine

subroutine swigc_minmax_element__SWIG_4(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_minmax_element__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_FUNPTR), value :: farg5
end subroutine

subroutine swigc_minmax_element__SWIG_5(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_minmax_element__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_FUNPTR), value :: farg5
end subroutine

subroutine swigc_minmax_element__SWIG_6(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_minmax_element__SWIG_6")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_FUNPTR), value :: farg5
end subroutine

subroutine swigc_minmax_element__SWIG_7(farg1, farg3, farg4, farg5) &
bind(C, name="_wrap_minmax_element__SWIG_7")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_FUNPTR), value :: farg5
end subroutine

function swigc_includes__SWIG_1(farg1, farg3) &
bind(C, name="_wrap_includes__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
integer(C_INT) :: fresult
end function

function swigc_includes__SWIG_2(farg1, farg3) &
bind(C, name="_wrap_includes__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
integer(C_INT) :: fresult
end function

function swigc_includes__SWIG_3(farg1, farg3) &
bind(C, name="_wrap_includes__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
integer(C_INT) :: fresult
end function

function swigc_includes__SWIG_4(farg1, farg3, farg5) &
bind(C, name="_wrap_includes__SWIG_4") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
integer(C_INT) :: fresult
end function

function swigc_includes__SWIG_5(farg1, farg3, farg5) &
bind(C, name="_wrap_includes__SWIG_5") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
integer(C_INT) :: fresult
end function

function swigc_includes__SWIG_6(farg1, farg3, farg5) &
bind(C, name="_wrap_includes__SWIG_6") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
integer(C_INT) :: fresult
end function

function swigc_includes__SWIG_7(farg1, farg3, farg5) &
bind(C, name="_wrap_includes__SWIG_7") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg3
type(C_FUNPTR), value :: farg5
integer(C_INT) :: fresult
end function

subroutine swigc_shuffle__SWIG_1(farg1, farg2) &
bind(C, name="_wrap_shuffle__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_shuffle__SWIG_2(farg1, farg2) &
bind(C, name="_wrap_shuffle__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_shuffle__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_shuffle__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_shuffle__SWIG_4(farg1, farg2) &
bind(C, name="_wrap_shuffle__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine SWIGTM_fin_int32_t_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  integer(C_INT32_T), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  integer(C_INT32_T), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
subroutine swigf_sort__SWIG_1(data)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), target :: data
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
call swigc_sort__SWIG_1(farg1)
end subroutine

subroutine SWIGTM_fin_int64_t_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  integer(C_INT64_T), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  integer(C_INT64_T), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
subroutine swigf_sort__SWIG_2(data)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), target :: data
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
call swigc_sort__SWIG_2(farg1)
end subroutine

subroutine SWIGTM_fin_double_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  real(C_DOUBLE), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  real(C_DOUBLE), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
subroutine swigf_sort__SWIG_3(data)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), target :: data
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
call swigc_sort__SWIG_3(farg1)
end subroutine

subroutine swigf_sort__SWIG_4(data, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), target :: data
procedure(flc_cmp_int4) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
call swigc_sort__SWIG_4(farg1, farg3)
end subroutine

subroutine swigf_sort__SWIG_5(data, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), target :: data
procedure(flc_cmp_int8) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
call swigc_sort__SWIG_5(farg1, farg3)
end subroutine

subroutine swigf_sort__SWIG_6(data, cmp)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), target :: data
procedure(flc_cmp_real8) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
call swigc_sort__SWIG_6(farg1, farg3)
end subroutine

subroutine SWIGTM_fin_void_Sm__Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  type(C_PTR), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  type(C_PTR), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
subroutine swigf_sort__SWIG_7(data, cmp)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), dimension(:), target :: data
procedure(flc_cmp_ptr) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_void_Sm__Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
call swigc_sort__SWIG_7(farg1, farg3)
end subroutine


subroutine SWIGTM_fout_bool(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  integer(kind=C_INT), intent(in) :: imout
  logical, intent(out) :: fout
  fout = (imout /= 0)
end subroutine

function swigf_is_sorted__SWIG_1(data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
fresult = swigc_is_sorted__SWIG_1(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_is_sorted__SWIG_2(data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
fresult = swigc_is_sorted__SWIG_2(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_is_sorted__SWIG_3(data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
real(C_DOUBLE), dimension(:), intent(in), target :: data
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
fresult = swigc_is_sorted__SWIG_3(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_is_sorted__SWIG_4(data, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT32_T), dimension(:), intent(in), target :: data
procedure(flc_cmp_int4) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_4(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_is_sorted__SWIG_5(data, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT64_T), dimension(:), intent(in), target :: data
procedure(flc_cmp_int8) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_5(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_is_sorted__SWIG_6(data, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
real(C_DOUBLE), dimension(:), intent(in), target :: data
procedure(flc_cmp_real8) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_6(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_is_sorted__SWIG_7(data, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
type(C_PTR), dimension(:), intent(in), target :: data
procedure(flc_cmp_ptr) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(C_FUNPTR) :: farg3 

call SWIGTM_fin_void_Sm__Sb__SB_(data, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_7(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

subroutine SWIGTM_fin_int_Sb__SB_(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  integer(C_INT), dimension(:), intent(in), target :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  integer(C_SIZE_T) :: sz
  integer(C_INT), pointer :: imtemp

  sz = size(finp, kind=C_SIZE_T)
  if (sz > 0_c_size_t) then
    imtemp => finp(1)
    iminp%data = c_loc(imtemp)
  else
    iminp%data = c_null_ptr
  end if
  iminp%size = sz
end subroutine
subroutine swigf_argsort__SWIG_1(data, idx)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
call swigc_argsort__SWIG_1(farg1, farg3)
end subroutine

subroutine swigf_argsort__SWIG_2(data, idx)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
call swigc_argsort__SWIG_2(farg1, farg3)
end subroutine

subroutine swigf_argsort__SWIG_3(data, idx)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
call swigc_argsort__SWIG_3(farg1, farg3)
end subroutine

subroutine swigf_argsort__SWIG_4(data, idx, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
procedure(flc_cmp_int4) :: cmp
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
call swigc_argsort__SWIG_4(farg1, farg3, farg5)
end subroutine

subroutine swigf_argsort__SWIG_5(data, idx, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
procedure(flc_cmp_int8) :: cmp
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
call swigc_argsort__SWIG_5(farg1, farg3, farg5)
end subroutine

subroutine swigf_argsort__SWIG_6(data, idx, cmp)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
procedure(flc_cmp_real8) :: cmp
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
call swigc_argsort__SWIG_6(farg1, farg3, farg5)
end subroutine

subroutine swigf_argsort__SWIG_7(data, idx, cmp)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), dimension(:), intent(in), target :: data
integer(C_INT), dimension(:), target :: idx
procedure(flc_cmp_ptr) :: cmp
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_void_Sm__Sb__SB_(data, farg1)
call SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
call swigc_argsort__SWIG_7(farg1, farg3, farg5)
end subroutine

function swigf_binary_search__SWIG_1(data, value) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT32_T), intent(in) :: value
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
integer(C_INT32_T) :: farg3 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = value
fresult = swigc_binary_search__SWIG_1(farg1, farg3)
swig_result = fresult
end function

function swigf_binary_search__SWIG_2(data, value) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT64_T), intent(in) :: value
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
integer(C_INT64_T) :: farg3 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = value
fresult = swigc_binary_search__SWIG_2(farg1, farg3)
swig_result = fresult
end function

function swigf_binary_search__SWIG_3(data, value) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
real(C_DOUBLE), dimension(:), intent(in), target :: data
real(C_DOUBLE), intent(in) :: value
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
real(C_DOUBLE) :: farg3 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = value
fresult = swigc_binary_search__SWIG_3(farg1, farg3)
swig_result = fresult
end function

function swigf_binary_search__SWIG_4(data, value, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT32_T), intent(in) :: value
procedure(flc_cmp_int4) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
integer(C_INT32_T) :: farg3 
type(C_FUNPTR) :: farg4 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_4(farg1, farg3, farg4)
swig_result = fresult
end function

function swigf_binary_search__SWIG_5(data, value, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT64_T), intent(in) :: value
procedure(flc_cmp_int8) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
integer(C_INT64_T) :: farg3 
type(C_FUNPTR) :: farg4 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_5(farg1, farg3, farg4)
swig_result = fresult
end function

function swigf_binary_search__SWIG_6(data, value, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
real(C_DOUBLE), dimension(:), intent(in), target :: data
real(C_DOUBLE), intent(in) :: value
procedure(flc_cmp_real8) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
real(C_DOUBLE) :: farg3 
type(C_FUNPTR) :: farg4 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_6(farg1, farg3, farg4)
swig_result = fresult
end function

function swigf_binary_search__SWIG_7(data, value, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(INDEX_INT) :: swig_result
type(C_PTR), dimension(:), intent(in), target :: data
type(C_PTR), intent(in) :: value
procedure(flc_cmp_ptr) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_FUNPTR) :: farg4 

call SWIGTM_fin_void_Sm__Sb__SB_(data, farg1)
farg3 = value
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_7(farg1, farg3, farg4)
swig_result = fresult
end function

subroutine swigf_equal_range__SWIG_1(data, value, first_index, last_index)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT32_T), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
type(SwigArrayWrapper) :: farg1 
integer(C_INT32_T) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
call swigc_equal_range__SWIG_1(farg1, farg3, farg4, farg5)
end subroutine

subroutine swigf_equal_range__SWIG_2(data, value, first_index, last_index)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT64_T), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
type(SwigArrayWrapper) :: farg1 
integer(C_INT64_T) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
call swigc_equal_range__SWIG_2(farg1, farg3, farg4, farg5)
end subroutine

subroutine swigf_equal_range__SWIG_3(data, value, first_index, last_index)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), intent(in), target :: data
real(C_DOUBLE), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
type(SwigArrayWrapper) :: farg1 
real(C_DOUBLE) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
call swigc_equal_range__SWIG_3(farg1, farg3, farg4, farg5)
end subroutine

subroutine swigf_equal_range__SWIG_4(data, value, first_index, last_index, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(C_INT32_T), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
procedure(flc_cmp_int4) :: cmp
type(SwigArrayWrapper) :: farg1 
integer(C_INT32_T) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_FUNPTR) :: farg6 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
call swigc_equal_range__SWIG_4(farg1, farg3, farg4, farg5, farg6)
end subroutine

subroutine swigf_equal_range__SWIG_5(data, value, first_index, last_index, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(C_INT64_T), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
procedure(flc_cmp_int8) :: cmp
type(SwigArrayWrapper) :: farg1 
integer(C_INT64_T) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_FUNPTR) :: farg6 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
call swigc_equal_range__SWIG_5(farg1, farg3, farg4, farg5, farg6)
end subroutine

subroutine swigf_equal_range__SWIG_6(data, value, first_index, last_index, cmp)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), intent(in), target :: data
real(C_DOUBLE), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
procedure(flc_cmp_real8) :: cmp
type(SwigArrayWrapper) :: farg1 
real(C_DOUBLE) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_FUNPTR) :: farg6 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
call swigc_equal_range__SWIG_6(farg1, farg3, farg4, farg5, farg6)
end subroutine

subroutine swigf_equal_range__SWIG_7(data, value, first_index, last_index, cmp)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), dimension(:), intent(in), target :: data
type(C_PTR), intent(in) :: value
integer(INDEX_INT), target, intent(inout) :: first_index
integer(INDEX_INT), target, intent(inout) :: last_index
procedure(flc_cmp_ptr) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_FUNPTR) :: farg6 

call SWIGTM_fin_void_Sm__Sb__SB_(data, farg1)
farg3 = value
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
call swigc_equal_range__SWIG_7(farg1, farg3, farg4, farg5, farg6)
end subroutine

subroutine swigf_minmax_element__SWIG_1(data, min_index, max_index)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
call swigc_minmax_element__SWIG_1(farg1, farg3, farg4)
end subroutine

subroutine swigf_minmax_element__SWIG_2(data, min_index, max_index)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
call swigc_minmax_element__SWIG_2(farg1, farg3, farg4)
end subroutine

subroutine swigf_minmax_element__SWIG_3(data, min_index, max_index)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
call swigc_minmax_element__SWIG_3(farg1, farg3, farg4)
end subroutine

subroutine swigf_minmax_element__SWIG_4(data, min_index, max_index, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
procedure(flc_cmp_int4) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_int32_t_Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
call swigc_minmax_element__SWIG_4(farg1, farg3, farg4, farg5)
end subroutine

subroutine swigf_minmax_element__SWIG_5(data, min_index, max_index, cmp)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
procedure(flc_cmp_int8) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_int64_t_Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
call swigc_minmax_element__SWIG_5(farg1, farg3, farg4, farg5)
end subroutine

subroutine swigf_minmax_element__SWIG_6(data, min_index, max_index, cmp)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
procedure(flc_cmp_real8) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_double_Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
call swigc_minmax_element__SWIG_6(farg1, farg3, farg4, farg5)
end subroutine

subroutine swigf_minmax_element__SWIG_7(data, min_index, max_index, cmp)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), dimension(:), intent(in), target :: data
integer(INDEX_INT), target, intent(inout) :: min_index
integer(INDEX_INT), target, intent(inout) :: max_index
procedure(flc_cmp_ptr) :: cmp
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_void_Sm__Sb__SB_(data, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
call swigc_minmax_element__SWIG_7(farg1, farg3, farg4, farg5)
end subroutine

function swigf_includes__SWIG_1(data1, data2) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT32_T), dimension(:), intent(in), target :: data1
integer(C_INT32_T), dimension(:), intent(in), target :: data2
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 

call SWIGTM_fin_int32_t_Sb__SB_(data1, farg1)
call SWIGTM_fin_int32_t_Sb__SB_(data2, farg3)
fresult = swigc_includes__SWIG_1(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_includes__SWIG_2(data1, data2) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT64_T), dimension(:), intent(in), target :: data1
integer(C_INT64_T), dimension(:), intent(in), target :: data2
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 

call SWIGTM_fin_int64_t_Sb__SB_(data1, farg1)
call SWIGTM_fin_int64_t_Sb__SB_(data2, farg3)
fresult = swigc_includes__SWIG_2(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_includes__SWIG_3(data1, data2) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
real(C_DOUBLE), dimension(:), intent(in), target :: data1
real(C_DOUBLE), dimension(:), intent(in), target :: data2
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 

call SWIGTM_fin_double_Sb__SB_(data1, farg1)
call SWIGTM_fin_double_Sb__SB_(data2, farg3)
fresult = swigc_includes__SWIG_3(farg1, farg3)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_includes__SWIG_4(data1, data2, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT32_T), dimension(:), intent(in), target :: data1
integer(C_INT32_T), dimension(:), intent(in), target :: data2
procedure(flc_cmp_int4) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_int32_t_Sb__SB_(data1, farg1)
call SWIGTM_fin_int32_t_Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_4(farg1, farg3, farg5)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_includes__SWIG_5(data1, data2, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT64_T), dimension(:), intent(in), target :: data1
integer(C_INT64_T), dimension(:), intent(in), target :: data2
procedure(flc_cmp_int8) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_int64_t_Sb__SB_(data1, farg1)
call SWIGTM_fin_int64_t_Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_5(farg1, farg3, farg5)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_includes__SWIG_6(data1, data2, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
real(C_DOUBLE), dimension(:), intent(in), target :: data1
real(C_DOUBLE), dimension(:), intent(in), target :: data2
procedure(flc_cmp_real8) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_double_Sb__SB_(data1, farg1)
call SWIGTM_fin_double_Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_6(farg1, farg3, farg5)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_includes__SWIG_7(data1, data2, cmp) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
type(C_PTR), dimension(:), intent(in), target :: data1
type(C_PTR), dimension(:), intent(in), target :: data2
procedure(flc_cmp_ptr) :: cmp
integer(C_INT) :: fresult 
type(SwigArrayWrapper) :: farg1 
type(SwigArrayWrapper) :: farg3 
type(C_FUNPTR) :: farg5 

call SWIGTM_fin_void_Sm__Sb__SB_(data1, farg1)
call SWIGTM_fin_void_Sm__Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_7(farg1, farg3, farg5)
call SWIGTM_fout_bool(fresult, swig_result)
end function

subroutine swigf_shuffle__SWIG_1(g, data)
use, intrinsic :: ISO_C_BINDING
class(MersenneEngine4), intent(in) :: g
integer(C_INT32_T), dimension(:), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = g%swigdata
call SWIGTM_fin_int32_t_Sb__SB_(data, farg2)
call swigc_shuffle__SWIG_1(farg1, farg2)
end subroutine

subroutine swigf_shuffle__SWIG_2(g, data)
use, intrinsic :: ISO_C_BINDING
class(MersenneEngine4), intent(in) :: g
integer(C_INT64_T), dimension(:), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = g%swigdata
call SWIGTM_fin_int64_t_Sb__SB_(data, farg2)
call swigc_shuffle__SWIG_2(farg1, farg2)
end subroutine

subroutine swigf_shuffle__SWIG_3(g, data)
use, intrinsic :: ISO_C_BINDING
class(MersenneEngine4), intent(in) :: g
real(C_DOUBLE), dimension(:), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = g%swigdata
call SWIGTM_fin_double_Sb__SB_(data, farg2)
call swigc_shuffle__SWIG_3(farg1, farg2)
end subroutine

subroutine swigf_shuffle__SWIG_4(g, data)
use, intrinsic :: ISO_C_BINDING
class(MersenneEngine4), intent(in) :: g
type(C_PTR), dimension(:), target :: data
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = g%swigdata
call SWIGTM_fin_void_Sm__Sb__SB_(data, farg2)
call swigc_shuffle__SWIG_4(farg1, farg2)
end subroutine


end module
